import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkOnly } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

declare const self: ServiceWorkerGlobalScope & typeof globalThis;

clientsClaim();

// Precache all assets generated by Next.js
precacheAndRoute(self.__WB_MANIFEST);

// Background Sync for Supabase
const bgSyncPlugin = new BackgroundSyncPlugin('supabase-sync', {
  maxRetentionTime: 24 * 60, // Retry for max 24 Hours
});

registerRoute(
  ({ url }) => url.href.includes('supabase.co'),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'POST'
);

// Runtime caching for images
registerRoute(
  ({ request }) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images',
  })
);

// Runtime caching for static assets
registerRoute(
  ({ request }) => request.destination === 'style' || request.destination === 'script' || request.destination === 'worker',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
  })
);
